### ISSUE TITLE
Failed 01_basic.t on Linux

### ISSUE THREAD

**Issue by syohex** [hideo55/p5-autolocale#1]
I failed test on Linux and got following message.

```
    #   Failed test 'in local scope'
    #   at t/01_basic.t line 14.
    #          got: 'C'
    #     expected: 'POSIX'

    #   Failed test 'lexical use'
    #   at t/01_basic.t line 26.
    #          got: 'C'
    #     expected: 'POSIX'

    #   Failed test 'out of lexical pragma'
    #   at t/01_basic.t line 30.
    #          got: 'C'
    #     expected: 'POSIX'
    # Looks like you failed 3 tests of 6.
```

Glibc's `setlocale` return `"C"` when it calls `setlocale(LC_ALL, "POSIX")`.
Because `"POSIX"` equals to `"C"`.

`setlocale` does not necessary return set string(2nd argument).

I think this may not be glibc's bug.
Please see [POSIX setlocale manpage](http://pubs.opengroup.org/onlinepubs/7908799/xsh/setlocale.html)

**Comment by hideo55** [comment]
Thanks!
It will be fixed in the next release.

**Comment by syohex** [comment]
Thanks. I successfully install autolocale 0.04 on Linux machine.
Close this issue.
